/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/yang/ui-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * UI 目录
         * @description 返回当前请求身份可访问的 Action 演示契约
         */
        get: operations["account.user.ui_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 授予权限
         * @description 授予目标用户一个已声明的权限（幂等）
         */
        post: operations["access.grants.grant_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/grants/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 撤销权限
         * @description 撤销目标用户的一个直授权限（幂等）
         */
        post: operations["access.grants.revoke_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 权限目录
         * @description 查询全部 Action 声明的权限集合
         */
        get: operations["access.grants.list_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/users/{user_id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 用户授权列表
         * @description 查询目标用户的全部直授权限
         */
        get: operations["access.grants.list_user_grants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建便签
         * @description 创建一条归属当前用户的便签
         */
        post: operations["demo.notes.create_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/notes/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除便签
         * @description 删除一条归属当前用户的便签
         */
        post: operations["demo.notes.delete_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/notes/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 便签列表
         * @description 分页查询当前用户的便签（仅本人数据）
         */
        post: operations["demo.notes.list_notes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/notes/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 更新便签
         * @description 更新一条归属当前用户的便签
         */
        post: operations["demo.notes.update_note"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改密码
         * @description 校验当前密码并使已有会话失效
         */
        post: operations["account.user.change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停用当前账号
         * @description 停用当前账号，并撤销此前签发的全部会话
         */
        post: operations["account.user.disable_self"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description 校验账号密码并签发 Token
         */
        post: operations["account.user.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 退出全部会话
         * @description 递增持久会话版本并撤销当前账号此前签发的全部 Access 与 Refresh Token
         */
        post: operations["account.user.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前用户
         * @description 读取当前已认证用户
         */
        get: operations["account.user.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 Token
         * @description 轮换 Refresh Token 并签发新 Token 对
         */
        post: operations["account.user.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册用户
         * @description 创建一个新用户
         */
        post: operations["account.user.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/registration-email-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发送注册邮箱验证码
         * @description 按邮箱、来源地址和全局容量限制投递一次性注册验证码
         */
        post: operations["account.user.request_registration_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置密码
         * @description 消费短期单次凭证并使已有会话失效
         */
        post: operations["account.user.reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code: number;
            data?: unknown;
            message: string;
        };
        /** @description 权限目录中的一个条目：权限字符串与声明它的操作 ID 列表。 */
        PermissionEntry: {
            declared_by: string[];
            permission: string;
        };
        /** @description 单条直授权限的对外视图。 */
        GrantView: {
            /** Format: int64 */
            granted_by: number;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            occurred_at: number;
            permission: string;
        };
        /** @description 排序条目（JSON 形态：`{"field": "id", "direction": "desc"}`）。 */
        OrderByItem: {
            /**
             * @description 方向，缺省为 Asc
             * @default Asc
             */
            direction: components["schemas"]["SortOrder"];
            /** @description 字段名 */
            field: string;
        };
        /** @description 排序方向。 */
        SortOrder: "Asc" | "Desc";
        /**
         * @description WHERE 条件枚举
         *
         *     定义各种查询条件类型，支持常见的 SQL WHERE 子句操作。
         *
         *     # 变体
         *
         *     - `Eq`：等于条件 (field = value) - `In`：包含于列表条件 (field IN (values)) - `Like`：模糊匹配条件 (field LIKE pattern) - `Gt`：大于条件 (field > value) - `Gte`：大于等于条件 (field >= value) - `Lt`：小于条件 (field < value) - `Lte`：小于等于条件 (field <= value) - `IsNull`：空值判断 (field IS NULL) - `IsNotNull`：非空值判断 (field IS NOT NULL)
         *
         *     # 示例
         *
         *     ```rust use yang_base::table::WhereCondition; use serde_json::json;
         *
         *     // 等于条件 let eq_condition = WhereCondition::Eq { field: "status".to_string(), value: json!("active"), };
         *
         *     // 包含条件 let in_condition = WhereCondition::In { field: "role".to_string(), values: vec![json!("admin"), json!("user")], };
         *
         *     // 模糊匹配 let like_condition = WhereCondition::Like { field: "name".to_string(), pattern: "%alice%".to_string(), };
         *
         *     // 大于条件 let gt_condition = WhereCondition::Gt { field: "age".to_string(), value: json!(18), };
         *
         *     // 空值判断 let is_null_condition = WhereCondition::IsNull { field: "deleted_at".to_string(), }; ```
         */
        WhereCondition: {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "eq";
            /** @description 比较值 */
            value: unknown;
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "in";
            /** @description 值列表 */
            values: unknown[];
        } | {
            /** @description 字段名 */
            field: string;
            /** @description 匹配模式 */
            pattern: string;
            /** @enum {string} */
            type: "like";
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "gt";
            /** @description 比较值 */
            value: unknown;
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "gte";
            /** @description 比较值 */
            value: unknown;
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "lt";
            /** @description 比较值 */
            value: unknown;
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "lte";
            /** @description 比较值 */
            value: unknown;
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "is_null";
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "is_not_null";
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "ne";
            /** @description 比较值 */
            value: unknown;
        } | {
            /** @description 字段名 */
            field: string;
            /** @description 区间上界 */
            hi: unknown;
            /** @description 区间下界 */
            lo: unknown;
            /** @enum {string} */
            type: "between";
        } | {
            /** @description 字段名 */
            field: string;
            /** @enum {string} */
            type: "not_in";
            /** @description 值列表 */
            values: unknown[];
        } | {
            /** @description 子条件列表 */
            conditions: components["schemas"]["WhereCondition"][];
            /** @enum {string} */
            type: "and";
        } | {
            /** @description 子条件列表 */
            conditions: components["schemas"]["WhereCondition"][];
            /** @enum {string} */
            type: "or";
        };
        /**
         * @description 用户账号只允许处于启用或停用状态。
         * @enum {string}
         */
        UserStatus: "active" | "disabled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "account.user.ui_catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "access.grants.grant_permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    permission: string;
                    /** Format: int64 */
                    user_id: number;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "access.grants.revoke_permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    permission: string;
                    /** Format: int64 */
                    user_id: number;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "access.grants.list_permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /** ListPermissionsResult */
                        data: {
                            permissions: components["schemas"]["PermissionEntry"][];
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "access.grants.list_user_grants": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /** ListUserGrantsResult */
                        data: {
                            grants: components["schemas"]["GrantView"][];
                            /** Format: int64 */
                            user_id: number;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "demo.notes.create_note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default null */
                    content?: string | null;
                    title: string;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "demo.notes.delete_note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    id: number;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "demo.notes.list_notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 是否额外执行 COUNT 查询
                     * @default false
                     */
                    count_total?: boolean;
                    /** @description 排序规则列表 */
                    order_by?: components["schemas"]["OrderByItem"][];
                    /**
                     * Format: uint32
                     * @description 页码（1 起步），缺省 1
                     * @default 1
                     */
                    page?: number;
                    /**
                     * Format: uint32
                     * @description 每页条数，缺省 10，必须 1..=100
                     * @default 10
                     */
                    page_size?: number;
                    /**
                     * @description 在表定义声明的 searchable 字段中执行关键词搜索。
                     * @default null
                     */
                    search?: string | null;
                    /**
                     * @description where 布尔过滤树（JSON key 为 `"where"`），缺省无条件
                     * @default null
                     */
                    where?: components["schemas"]["WhereCondition"] | null;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ListNotesResult
                         * @description 标准分页行数据输出。
                         */
                        data: {
                            items: {
                                [key: string]: unknown;
                            }[];
                            /** Format: uint32 */
                            page: number;
                            /** Format: uint32 */
                            page_size: number;
                            /** Format: uint64 */
                            total?: number | null;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "demo.notes.update_note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default null */
                    content?: string | null;
                    /** Format: int64 */
                    id: number;
                    /** @default null */
                    title?: string | null;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.change_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    new_password: string;
                    old_password: string;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.disable_self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description 可选业务扩展字段。
                     * @default null
                     */
                    extra?: unknown;
                    /** @description 登录凭据。 */
                    password: string;
                    /** @description 用户名、邮箱或其他登录标识。 */
                    username: string;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * UserView
                         * @description 可安全返回给客户端的用户视图，不包含密码摘要。
                         */
                        data: {
                            /** Format: int64 */
                            created_at: number;
                            email?: string | null;
                            /** Format: int64 */
                            email_verified_at?: number | null;
                            /** Format: int64 */
                            id: number;
                            status: components["schemas"]["UserStatus"];
                            /** Format: int64 */
                            updated_at: number;
                            username: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    email_code: string;
                    password: string;
                    username: string;
                };
            };
        };
        responses: {
            /** @description 成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * UserView
                         * @description 可安全返回给客户端的用户视图，不包含密码摘要。
                         */
                        data: {
                            /** Format: int64 */
                            created_at: number;
                            email?: string | null;
                            /** Format: int64 */
                            email_verified_at?: number | null;
                            /** Format: int64 */
                            id: number;
                            status: components["schemas"]["UserStatus"];
                            /** Format: int64 */
                            updated_at: number;
                            username: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.request_registration_email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description 成功 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * RegistrationEmailCodeAccepted
                         * @description 验证码请求被接受后的通用响应（不暴露身份是否真实存在）。
                         */
                        data: {
                            /** @description 请求已被接受（不保证邮件真实投递）。 */
                            accepted: boolean;
                            /**
                             * Format: uint64
                             * @description 验证码有效期（秒）。
                             */
                            expires_in: number;
                            /**
                             * Format: uint64
                             * @description 重发冷却（秒）。
                             */
                            resend_after: number;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "account.user.reset_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    new_password: string;
                    reset_token: string;
                };
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: 0;
                        /**
                         * ApiResponse
                         * @description API 响应
                         *
                         *     统一的 API 响应格式，用于所有 Action 的返回值
                         *
                         *     # 字段
                         *
                         *     - `code`: 状态码（0 表示成功，非零表示失败） - `message`: 响应消息 - `data`: 响应数据（可选）
                         *
                         *     标注 `#[non_exhaustive]`：未来新增字段不构成破坏性变更。 请使用 [`ApiResponse::success`] / [`ApiResponse::fail`] / [`ApiResponse::from_error`] 等构造。
                         *
                         *     # 示例
                         *
                         *     ```rust,ignore use yang_base::action::ApiResponse; use serde_json::json;
                         *
                         *     // 创建成功响应 let response = ApiResponse::success( json!({ "id": 123, "name": "Alice" }), "操作成功" ); assert_eq!(response.code, 0);
                         *
                         *     // 创建失败响应 let response = ApiResponse::fail(400001, "参数错误"); assert_eq!(response.code, 400001); assert!(response.data.is_none()); ```
                         */
                        data: {
                            /**
                             * Format: int32
                             * @description 状态码
                             *
                             *     - 0: 成功 - 非零: 失败（具体错误码由业务定义）
                             */
                            code: number;
                            /**
                             * @description 响应数据
                             *
                             *     成功时包含业务数据，失败时通常为 None
                             */
                            data?: unknown;
                            /**
                             * @description 响应消息
                             *
                             *     描述操作结果的文本信息
                             */
                            message: string;
                        };
                        message: string;
                    };
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 服务器内部错误 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
